### ISSUE TITLE
OSX M1Max not able to render

### ISSUE THREAD

**Issue by tlightsky** [Linyou/taichi-ngp-renderer#15]
```
(taichi-ngp-renderer) ➜  taichi-ngp-renderer git:(main) python taichi_ngp.py --gui --scene lego
[Taichi] version 1.6.0, llvm 16.0.0git, commit 2d786e52, osx, python 3.8.13
Traceback (most recent call last):
  File "taichi_ngp.py", line 1110, in <module>
    main(args)
  File "taichi_ngp.py", line 1052, in main
    NGP_fw.taichi_init(args.print_profile)
  File "taichi_ngp.py", line 408, in taichi_init
    ti.init(
  File "/Users/me/source/cpp/taichi/python/taichi/lang/misc.py", line 455, in init
    cfg.arch = adaptive_arch_select(arch, enable_fallback)
  File "/Users/me/source/cpp/taichi/python/taichi/lang/misc.py", line 766, in adaptive_arch_select
    raise RuntimeError(f'Arch={arch} is not supported')
RuntimeError: Arch=[<Arch.vulkan: 12>] is not supported
```

**Comment by Linyou** [comment]
Hi @tlightsky 
So, it looks like the problem could be because of Taichi 1.6. I'll dig into it and try to fix it ASAP. You could use the older version (1.4.1) to avoid this issue for now.

**Comment by tlightsky** [comment]
> Hi @tlightsky So, it looks like the problem could be because of Taichi 1.6. I'll dig into it and try to fix it ASAP. You could use the older version (1.4.1) to avoid this issue for now.

Thank you!
So m1max OSX vulkan should be able to run it right?
