### ISSUE TITLE
Dispatch error when using Vulkan backend on Intel integrated graphics

### ISSUE THREAD

**Issue by victoriacity** [Linyou/taichi-ngp-renderer#8]
```
python taichi_ngp.py
[Taichi] version 1.4.1, llvm 15.0.1, commit e67c674e, win, python 3.9.13
[W 02/25/23 12:58:49.450 4244] [cuda_driver.cpp:taichi::lang::CUDADriverBase::load_lib@36] nvcuda.dll lib not found.
[Taichi] Starting on arch=vulkan
Loading model from ./npy_models/lego.npy
[E 02/25/23 12:58:49.785 4244] [runtime.cpp:taichi::lang::gfx::GfxRuntime::launch_kernel@519] Dispatch error : RhiResult(-3)


Traceback (most recent call last):
  File "C:\taichi\taichi-ngp-renderer\taichi_ngp.py", line 1177, in <module>
    main(args)
  File "C:\taichi\taichi-ngp-renderer\taichi_ngp.py", line 1147, in main
    ngp.load_model(npy_file)
  File "C:\taichi\taichi-ngp-renderer\taichi_ngp.py", line 358, in load_model
    self.hash_embedding.from_numpy(np_hash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\field.py", line 357, in from_numpy
    self._from_external_arr(arr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\util.py", line 310, in wrapped
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\field.py", line 347, in _from_external_arr
    ext_arr_to_tensor(arr, self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\kernel_impl.py", line 974, in wrapped
    return primal(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\kernel_impl.py", line 901, in __call__
    return self.runtime.compiled_functions[key](*args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\kernel_impl.py", line 826, in func__
    raise e from None
  File "C:\ProgramData\Anaconda3\lib\site-packages\taichi\lang\kernel_impl.py", line 823, in func__
    t_kernel(launch_ctx)
RuntimeError: [runtime.cpp:taichi::lang::gfx::GfxRuntime::launch_kernel@519] Dispatch error : RhiResult(-3)
```

GPU device properties from `vulkaninfo`:
```
Device Properties and Extensions:
=================================
GPU0:
VkPhysicalDeviceProperties:
---------------------------
        apiVersion        = 4206814 (1.3.222)
        driverVersion     = 1658142 (0x194d1e)
        vendorID          = 0x8086
        deviceID          = 0x46a8
        deviceType        = PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
        deviceName        = Intel(R) Iris(R) Xe Graphics
        pipelineCacheUUID = 2c3f2a36-2b35-1837-273a-243423302101
```

**Comment by Linyou** [comment]
Hi~ @victoriacity 

I don't have an intel integrated GPU to test this issue, but according to the log messages, the error appears when `from_numpy` is called. 

Could you write another script to test `from_numpy`? So we can make sure this is not a `Taichi` issue

**Comment by chenzhekl** [comment]
I am having the same problem with Vulkan backend + AMD cards. The problem persists after isolating the hash embedding loading code from the rest of the script. It might be a Taichi problem.

Seems to be related to: https://github.com/taichi-dev/taichi/issues/7674
